// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"Week04/app"
	"Week04/app/web"
	"Week04/config"
	"Week04/internal/biz"
	"Week04/internal/dao"
	"Week04/internal/router"
	"Week04/internal/service"
	"Week04/library/logger"
)

// Injectors from wire.go:

func BuildApp(path2 string) (*app.App, error) {
	configConfig := config.NewConfig(path2)
	engine := app.NewGinEngine()
	logrusLogger := logger.New()
	bizRecover := biz.NewRecover(logrusLogger)
	db, err := dao.NewDatabaseMYSQL(configConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	daoDao := dao.NewDao(logrusLogger, db)
	userService := service.NewService(daoDao, logrusLogger)
	userController := biz.NewUserController(logrusLogger, userService)
	routerRouter := router.NewRouter(bizRecover, userController)
	server := web.NewServer(engine, routerRouter, logrusLogger, configConfig)
	appApp := app.NewApp(configConfig, server)
	return appApp, nil
}
