#To-Do:可以集成go-bindata/fsnotify 热更新配置
Server:
  HttpPort: 8000
Database:
  DBType: mysql
  UserName: root
  Password: rootroot
  Host: 127.0.0.1:3306
  DBName: user
  #TablePrefix: _
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30